apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-smtp-rabbitmq
  namespace: scat
  labels:
    purpose: smtp-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: smtp-rabbitmq
  template:
    metadata:
      namespace: scat
      labels:
        purpose: smtp-rabbitmq
    spec:
      containers:
      - name: smtp-rabbitmq
        image: pswargam/scatrabbitmq:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1883
        - containerPort: 4369
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 25672
